// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package backend.protocol;

public interface GreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:backend.protocol.GreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
