// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package backend.protocol;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:backend.protocol.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
